### ISSUE TITLE
Add SIG data

### ISSUE THREAD

**Issue by Mini256** [ti-community-infra/devstats#20]

**Comment by hi-rustin** [comment]
In my opinion, maybe we can redesign the sig data structure and store it directly on pg. Since the old robot is basically migrated at the moment, the sig data can be migrated.

**Comment by hi-rustin** [comment]
I will submit a RFC for it.

**Comment by hi-rustin** [comment]
We've recently made changes to the overall community governance and may remove the SIG, so I've decided to close this issue for now.
